### ISSUE TITLE
Tha Navbar is not responsive for some screen sizes.

### ISSUE THREAD

**Issue by shrutigolwalk0109** [J0SAL/Decentralized-Expense-Tracker#102]
### Description

Please assign me this issue, I would like to work on it. (with the label of GSSoC).

### Screenshots

#Screenshot 

https://github.com/J0SAL/Decentralized-Expense-Tracker/assets/132553685/d287b0d4-3417-4808-95d7-70d96978db98

**Comment by J0SAL** [comment]
Go ahead!🚀

**Comment by J0SAL** [comment]
Hey, @shrutigolwalk0109 as #50 no longer exists, I am reopening the issue, let me know if you want to work on the same

**Comment by shrutigolwalk0109** [comment]
Yes , I want to work on it .

**Comment by J0SAL** [comment]
Hey @shrutigolwalk0109, will you be working on the new PR? Or are you unassigning yourself?

**Comment by CodeitVasu** [comment]
Can I work under this issue? I wish to take it under the gssoc'23 program

**Comment by J0SAL** [comment]
closing the issue, as it's no longer needed
