### ISSUE TITLE
Want to add contact page in the website

### ISSUE THREAD

**Issue by lakhan06** [J0SAL/Decentralized-Expense-Tracker#104]
### Is your feature request related to a problem? Please describe.

There is no contact page in the website so i want to add one .

### Describe the solution you'd like

I will a good responsive contact page 

### Describe alternatives you've considered

i can also  improve the hero section of website

### Additional context

Below is an sample design of contact page

![image](https://github.com/J0SAL/Decentralized-Expense-Tracker/assets/119161467/e42e94cd-4867-4fc1-b1be-840730748a5e)

@J0SAL  Please assign me this issue

**Comment by J0SAL** [comment]
Actually, there is a plan to implement a chatbot that can resolve doubts, or email any queries to the project owners, so we don't need the contact page as of now.
