### ISSUE TITLE
Want to add hover effect on the icon

### ISSUE THREAD

**Issue by HimanshuNarware** [J0SAL/Decentralized-Expense-Tracker#106]
### Is your feature request related to a problem? Please describe.

I want to add hover effect on the icons of the wallet.

### Describe the solution you'd like

Adding a hover effect on the wallet icons

### Describe alternatives you've considered

Improve the UI of the website

### Additional context

![12](https://github.com/J0SAL/Decentralized-Expense-Tracker/assets/83147410/1a474006-2380-48c6-85a3-1305445b402f)

**Comment by J0SAL** [comment]
I believe there is enough highlight on hover, that does the job ... as we can see from about screenshot itself.
