### ISSUE TITLE
frontend broken?

### ISSUE THREAD

**Issue by Anurag-Raut** [J0SAL/Decentralized-Expense-Tracker#11]
Is the problem with my local setup or the frontend is broken ?
![image](https://github.com/J0SAL/Decentralized-Expense-Tracker/assets/102049482/a2abfc2d-7ac1-457a-8f28-666bc01c7d73)
 also all the graphs and their labels are blurry 
![image](https://github.com/J0SAL/Decentralized-Expense-Tracker/assets/102049482/3889204d-6e10-410d-b41c-535b64006bd9)

**Comment by J0SAL** [comment]
Hi @Anurag-Raut!

Maybe it triggered some edge case :/
It would be great if you can find the problem and fix it via PR.

Also in the issue description, you can add steps to reproduce so that other contributors can help you out.
