### ISSUE TITLE
Add netword/chain details on homepage

### ISSUE THREAD

**Issue by shobhitexe** [J0SAL/Decentralized-Expense-Tracker#110]
### Is your feature request related to a problem? Please describe.

Currently while we visit homepage theres only one button is there for connect wallet which might not be the best and should be changed

### Describe the solution you'd like

And i think details like 
Network / Chain or if we are using testnet such as sepolia should be present in homepage if not on homepage on other page 
also with the details of networks and specially which testnet to user will be very helpful to first time visitor 
and can prevent unusual bugs

**Comment by shobhitexe** [comment]
> @shobhitexe I want the login to be a single-step process, similar to the OAuth functionality which makes it simple and easy (just a one-click thing)
> 
> but the issue you pointed out is valid too... in that case, can we give an option to switch chains after the user has logged on with an account, something similar to what is provided in https://testnets.opensea.io/ ?

Yes we can also do that but does your contract deployed or supports multichain?

**Comment by J0SAL** [comment]
@shobhitexe, Currently it can only support, hardhat, and goerli but sepolia and mumbai-testnet are in development, will be live soon

**Comment by shobhitexe** [comment]
> @shobhitexe, Currently it can only support, hardhat, and goerli but sepolia and mumbai-testnet are in development, will be live soon

Got it , so should we proceed with this issue or close it for now

**Comment by J0SAL** [comment]
you can start working on the issue

**Comment by shobhitexe** [comment]
hey sorry things happened and i got engaged in some issues wont be able to do this now no point of delaying it so unassigning it
