### ISSUE TITLE
Enhance footer

### ISSUE THREAD

**Issue by MisterMickey** [J0SAL/Decentralized-Expense-Tracker#111]
### Is your feature request related to a problem? Please describe.

The footer section in not properly designed, anchor tags are not styled that's why It's very tough to read what written.

I want to enhance the footer section. Kindly assign me this under gssoc23

### Describe the solution you'd like

![Screenshot from 2023-06-22 06-48-53](https://github.com/J0SAL/Decentralized-Expense-Tracker/assets/93720428/f76ab625-b6c1-4ad2-9237-8cf909fbbad4)

**Comment by J0SAL** [comment]
You can check #26 and propose your changes there
