### ISSUE TITLE
Enhance add Wallet Pop Up

### ISSUE THREAD

**Issue by MisterMickey** [J0SAL/Decentralized-Expense-Tracker#112]
### Is your feature request related to a problem? Please describe.

The hover effect is not so clear now in the add wallet Pop Up, The background color on hover is very light and that's why it's not visible much.

Kindly assign me this issue underg gssoc23

### Describe the solution you'd like

![Screenshot from 2023-06-22 06-51-43](https://github.com/J0SAL/Decentralized-Expense-Tracker/assets/93720428/ad87e19c-f120-4234-9c71-8b4ea3b1c76a)

**Comment by J0SAL** [comment]
we don't need it for now
