### ISSUE TITLE
Adding appropriate logo 

### ISSUE THREAD

**Issue by Prajwal0225** [J0SAL/Decentralized-Expense-Tracker#117]
### Is your feature request related to a problem? Please describe.

currently, this website is showing the  default react icon 
![react logo](https://github.com/J0SAL/Decentralized-Expense-Tracker/assets/103810119/4de87eef-9260-41fd-b763-dbcc5180c074)
,

### Describe the solution you'd like

I would like to add a more appropriate icon 
Like Bitcoin or money logo.

### Additional context

Can you please assign this issue to me under gssoc'23? So that I can start working on it.

**Comment by J0SAL** [comment]
Can you share the logo which you plan to include?
If it's good, then you can include it in both logo and favicon (browser icon)

**Comment by Prajwal0225** [comment]
![logo__](https://github.com/J0SAL/Decentralized-Expense-Tracker/assets/103810119/a344e316-57b6-4364-afb1-842debb50e03)

**Comment by J0SAL** [comment]
Looks good, go ahead! @Prajwal0225 🚀
