### ISSUE TITLE
Adding appropriate favicon to the website 

### ISSUE THREAD

**Issue by Prajwal0225** [J0SAL/Decentralized-Expense-Tracker#118]
### Is your feature request related to a problem? Please describe.

currently, this website is showing the  default nextjs  favicon

![favicon express](https://github.com/J0SAL/Decentralized-Expense-Tracker/assets/103810119/01e8fbdc-c647-485f-aa9c-10ac18869dc1)

### Describe the solution you'd like

I would like to add a more appropriate favicon to the website.

### Additional context

**Can you please assign this issue to me under gssoc'23? So that I can start working on it.**

**Comment by J0SAL** [comment]
#117
