### ISSUE TITLE
UI - height of Navbar

### ISSUE THREAD

**Issue by yashpreet2707** [J0SAL/Decentralized-Expense-Tracker#119]
### Describe the bug

Increased the height of the navbar, the previous one is not looking good I feel, moreover shifted the *Overview* a bit down. Assign me if you feel the same, or else close this issue. Have a good day.

<img width="1440" alt="Screenshot 2023-06-27 at 2 40 01 AM" src="https://github.com/J0SAL/Decentralized-Expense-Tracker/assets/111020648/a04f5354-7735-49b9-999d-780a92f5bcfa">

### Expected behaviour

<img width="1440" alt="Screenshot 2023-06-27 at 2 39 49 AM" src="https://github.com/J0SAL/Decentralized-Expense-Tracker/assets/111020648/4869c4ac-b6d6-4453-8c67-5140f95abd1a">

**Comment by J0SAL** [comment]
The current size of Navbar is perfect considering the amount of components it has
