### ISSUE TITLE
Admin page and Billing Information

### ISSUE THREAD

**Issue by Cdggtt** [J0SAL/Decentralized-Expense-Tracker#12]
If user open website then he/she login on the website and then fill the information like Name, Email Address, phone number and Country.

**Comment by Shashwat0227** [comment]
Hey can you assign me this issue i can work on it and make an interface for the following

**Comment by Suchitra-Sahoo** [comment]
Hello @J0SAL 
I recently came across your project and I'm excited about the opportunity to contribute under GSoC'23 by creating an admin page and implementing billing functionality.
I have prior experience in web development, particularly Css, Html, bootstrap and javascript. 
I look forward to the possibility of working with you and making valuable contributions to your project.

Best regards,
Suchitra Sahoo

**Comment by Cdggtt** [comment]
I can work on it.

**Comment by J0SAL** [comment]
Hey everyone,
thanks for showing interest!
but I want you'll to think in terms of the Expense Tracker Application, generally, you don't need things like `Name/Email Address/phone number /Country` while tracking your expenses.

please feel to share if you have some other ideas/opinions

**Comment by J0SAL** [comment]
@Cdggtt @Shashwat0227 As there is no response, I'll be closing this issue.
