### ISSUE TITLE
Want to add styling to the scroll bar of the website

### ISSUE THREAD

**Issue by HimanshuNarware** [J0SAL/Decentralized-Expense-Tracker#121]
### Is your feature request related to a problem? Please describe.

Scrollbar is missing styling

### Describe the solution you'd like

I want to add styling to the scroll bar of the website.it will improve the UI of the website.

### Additional context

![112](https://github.com/J0SAL/Decentralized-Expense-Tracker/assets/83147410/945ff207-4cc4-4e82-989b-2541f99e58b4)

**Comment by J0SAL** [comment]
We don't need this for now
