### ISSUE TITLE
Enable lazy loading to improve website performance

### ISSUE THREAD

**Issue by shraddha761** [J0SAL/Decentralized-Expense-Tracker#123]
### Is your feature request related to a problem? Please describe.

Lazy loading is a technique that can be used to improve the performance of a website by delaying the loading of images and other resources until they are needed. This can help to reduce the initial load time of a page, which can improve the user experience and make the website more responsive.

### Describe the solution you'd like

The benefits of lazy loading include:

Reduced initial load time
Improved user experience
More responsive website
Increased SEO ranking

### Additional context

Assign this issue to me under GSSOC'23

**Comment by J0SAL** [comment]
go ahead! @shraddha761 🚀

**Comment by shraddha761** [comment]
@J0SAL I am going to implement lazy loading in home page

**Comment by J0SAL** [comment]
@shraddha761  Do you mean all the components, including Graphs? Charts and forms?

**Comment by shraddha761** [comment]
![Screenshot 2023-07-08 192432](https://github.com/J0SAL/Decentralized-Expense-Tracker/assets/106100728/62beeb52-32ba-4966-9716-8eadd020b3d4)


Sry for the delay.
You can see the graph after implementing lazy loading and it optimize the website a lot

**Comment by Abhijit25Mishra** [comment]
@shraddha761 can you also show the score before the changes were made ?

**Comment by shraddha761** [comment]
@Abhijit25Mishra Yahh sure 

before 


![image](https://github.com/J0SAL/Decentralized-Expense-Tracker/assets/106100728/6acac9cb-5bcd-4723-81a9-ceeaabc9bca0)

**Comment by shraddha761** [comment]
@Abhijit25Mishra Please review this pr

**Comment by Abhijit25Mishra** [comment]
@J0SAL i am not able to view the deployment on vercel. it is one of the checks on github. can you verify this data ? cause i dont think so there should be such a big improvement. having said that i might very well be wrong.

**Comment by J0SAL** [comment]
@Abhijit25Mishra is this link not working on your end, https://jarvis-g9xfg1fjb-j0sal.vercel.app/ ?

**Comment by Abhijit25Mishra** [comment]
sorry my bad i was trying to view an older deplyment.

**Comment by Abhijit25Mishra** [comment]
there is about 150ms improvement. @J0SAL

**Comment by Abhijit25Mishra** [comment]
i dont know why but the first paint is always slower in her fork. I think that lazy loading is causing somethings to get slowed down the first time they are loaded.

so what i mean is a new user when they open the page for the first time, it will take about 1-3 sec more. but every other time they load that page it will be about 150ms better. @J0SAL

**Comment by J0SAL** [comment]
I feel the only thing it is lacking is the initial load, maybe we can turn it into a feature by providing a good, animated loading screen. (in a diff issue), what do you think @Abhijit25Mishra?

**Comment by Abhijit25Mishra** [comment]
hmm sounds great, i have done this before in a project. (https://enlace-umber.vercel.app/) we actually had similar reasons, as the site was too heavy to load we gave it like 4 sec loading screen animation. used anime.js, you can find the code here -> https://github.com/iiitkottayam/Enlace/tree/main/Enlace-main

**Comment by Abhijit25Mishra** [comment]
@shraddha761 have a look once. if you have any trouble let me know. 
also i would suggest you to look into other options, like gsap(greensock) and 3js, these two are also great but will probably require a lot of effort. have a look into this if you want to.

**Comment by Abhijit25Mishra** [comment]
@J0SAL if we plan to go ahead with this make sure to increse the level from 2 to 3.

**Comment by shraddha761** [comment]
@Abhijit25Mishra thank you, I was also thinking for the same but don't know how to implement I'll try my best and take help from you

**Comment by shraddha761** [comment]
@J0SAL Please merge this pr so that I can work on another one

**Comment by J0SAL** [comment]
@shraddha761 you can update the same code, instead of a new PR I'll make the current one into level3, sound good? @Abhijit25Mishra @shraddha761 ?
