### ISSUE TITLE
Enhancement of UI  on Landing page and adding About Us page.

### ISSUE THREAD

**Issue by tanya172** [J0SAL/Decentralized-Expense-Tracker#124]
### Is your feature request related to a problem? Please describe.

Hello, I am interested in improving the UI and landing page of the website. It's important to have an about us page for a website as anyone who visits the website should know what are the services being provided to the website.

### Describe the solution you'd like

I want to improve the page's footer and the navbar's UI as well. Furthermore, I want to add an About Us page to the website.

**Comment by J0SAL** [comment]
please check the previous issues, you can discuss your approach there,
about us: #101
home page: #49 
footer: #29
navbar: #102 

please add more specific details if there is anything else you want to add.

**Comment by tanya172** [comment]
Ok, no problem.
