### ISSUE TITLE
Add AI Chat and Voice Assistant for FAQ, Navigation, and User Experience Improvement in Web3 Expense Tracker Website

### ISSUE THREAD

**Issue by Nishitbaria** [J0SAL/Decentralized-Expense-Tracker#129]
### Is your feature request related to a problem? Please describe.

The Web3 Expense Tracker website would greatly benefit from the addition of an AI Chat and Voice Assistant to enhance the user experience by providing support for Frequently Asked Questions (FAQ), page navigation, and overall user interaction.

### Describe the solution you'd like

1. Integrate an AI Chat and Voice Assistant feature using a suitable library or API to provide interactive support to users visiting the Web3 Expense Tracker website.
2. Design and implement a chat interface that allows users to interact with the AI Assistant and receive instant responses to their queries.
3. Create a FAQ section within the website where users can find answers to commonly asked questions related to expense tracking, account management, and other relevant topics.
4. Configure the AI Assistant to provide accurate and helpful responses to user queries regarding the expense tracker functionalities, navigation within the website, and any other related information.
5. Implement voice recognition functionality, if feasible, to allow users to interact with the AI Assistant using voice commands or questions.
6. Ensure error handling and fallback mechanisms are in place to handle unexpected queries or cases where the AI Assistant is unable to provide a satisfactory response.
7. Conduct thorough testing to ensure the AI Chat and Voice Assistant functions correctly, responds accurately to user queries, and enhances the overall user experience.
8. Update the documentation or README file to provide instructions on how to interact with the AI Assistant and take advantage of its capabilities.

###  Screenshots
![image](https://github.com/pranjay-poddar/Dev-Geeks/assets/85815172/0ecaf2b4-7e2b-4314-9dff-a551fe69e2d4)
![image](https://github.com/NageshMandal/Engineering-Notes-Website/assets/85815172/800574ab-5aab-4b96-9d30-ba5b27d29a19)

@J0SAL ,please assign me this issue ,i will make pull request in a day

**Comment by J0SAL** [comment]
There is already a Voice Assistant (Speechly) present in the application, but for some reason, it doesn't work in production (works on localhost). As using 2 assistants would mess things up, could you either 
- replicate the functionality for Speechly into your AI Assistant? (if yes then we can remove speechly's dependency) 
- you could work on resolving the error with speechly.

Let me know which one you want to work on

**Comment by Nishitbaria** [comment]
@J0SAL ,I will   repliacte all fucntionality of your asistant in mine ,my asistant can answer any relevant question,provide navigation and also can answer general questions.please assign me this issue

**Comment by J0SAL** [comment]
cool, go ahead @Nishitbaria! 🚀
I hope you have checked the functionality where the assistant will be filling the form data based on voice commands
