### ISSUE TITLE
url links not working

### ISSUE THREAD

**Issue by akshaya-hub** [J0SAL/Decentralized-Expense-Tracker#13]
URL links in walletconnect desktop mode for a few cases are not working

**Comment by akshaya-hub** [comment]
can anyone find the URL links in the code i was unable to find

**Comment by harshsingh32** [comment]
I would like to work on this issue, please assign this issue to me under GSSoC'23.

**Comment by Suchitra-Sahoo** [comment]
Hello @J0SAL 
 I came across the issue regarding non-working URL links in the project and would like to offer my assistance in resolving this issue.With my experience in web development and troubleshooting, specifically in HTML, CSS, and JavaScript, I am confident in my ability to fix the non-working URL links effectively. 
I'm eager to contribute to your project and help resolve this issue.I look forward to your response.
Best Regards
Suchitra Sahoo

**Comment by akshaya-hub** [comment]
@harshsingh32 @Suchitra-Sahoo So, did you notice the error in  frontend can you tell me in which file the URLs are located

**Comment by J0SAL** [comment]
Hi, @akshaya-hub @Suchitra-Sahoo @harshsingh32, 
it would be better if you could add screenshots in your **issue description** to get more context.

**Comment by akshaya-hub** [comment]
@J0SAL kk i will add

**Comment by Riya2103** [comment]
I would like to contribute

**Comment by hansu03** [comment]
I would like to contribute
