### ISSUE TITLE
Overlapping Text

### ISSUE THREAD

**Issue by akanksha984** [J0SAL/Decentralized-Expense-Tracker#131]
### Describe the bug

![image](https://github.com/J0SAL/Decentralized-Expense-Tracker/assets/97845909/6ec31097-e0c7-4279-98ae-7303be7f245f)

### Expected behaviour

The text comment and login is overlapping thus we cannot see the text beneath it. Please assign it to me under gssoc'23. I want to work upon this issue

**Comment by J0SAL** [comment]
Oh, I think you tried one of the preview links given in the PRs. 
You won't find that option in the production/main link i.e. https://your-jarvis.vercel.app/ @akanksha984

**Comment by Harshsaini001** [comment]
@akanksha984 , I  want to work on this issue please assign me this
