### ISSUE TITLE
Adding a chatbot on the landing page.

### ISSUE THREAD

**Issue by SrishtiSonam** [J0SAL/Decentralized-Expense-Tracker#132]
### Is your feature request related to a problem? Please describe.

The user get a little confused where to go and what to do for they requirements......

### Describe the solution you'd like

The chatbot will allow the user to explore the website fully.

Give the direction to user where to go and what to do after getting on landing page.

It will answer the frequently asked questions. [FAQ]
Show the best use of the website for the user.
Give Suggestions - which suits best according to user choice.

### Describe alternatives you've considered

An "About us" or "FAQ" page link at landing page.

### Additional context

Assign me under Gssoc'2023.

**Comment by J0SAL** [comment]
@SrishtiSonam  I would not recommend a chatbot as it would lead to inefficiency with the existing voice assistant, instead, can you provide a similar feature through [react-joyride](https://www.npmjs.com/package/react-joyride)?

**Comment by SrishtiSonam** [comment]
No as I don't have much idea about react-joyride...

**Comment by J0SAL** [comment]
Okay then I'm closing the issue
