### ISSUE TITLE
[DOCS] Fix text in README

### ISSUE THREAD

**Issue by Sriparno08** [J0SAL/Decentralized-Expense-Tracker#133]
### Description

The word 'Variables' is spelt incorrect.

### Screenshots

![image](https://github.com/J0SAL/Decentralized-Expense-Tracker/assets/89148144/24ab34e8-dd22-4b99-9d37-2830ed189cf7)

### Additional information

I want to contribute as part of GSSoC'23.

**Comment by J0SAL** [comment]
I had a talk with the team and finalized that this type of issue is too small to be assigned under gssoc. do you still want to continue and address this issue (without it being under Gssoc)?

**Comment by Sriparno08** [comment]
Currently, I am trying to make contributions under GSSoC'23. So I think I won't be able to address this issue now.
