### ISSUE TITLE
[DOCS] Spelling mistakes in README file

### ISSUE THREAD

**Issue by blindaks** [J0SAL/Decentralized-Expense-Tracker#136]
### Description

There are some spelling mistakes and grammatical errors in the README file.
for eg, "throughout" is misspelled as "throught".

### Screenshots

![Screenshot (58)](https://github.com/J0SAL/Decentralized-Expense-Tracker/assets/128223364/4cffe511-15a5-4c24-96da-f9a6195947c4)
![Screenshot (59)](https://github.com/J0SAL/Decentralized-Expense-Tracker/assets/128223364/21ef3e61-155d-4714-ab32-4329243885e0)

**Comment by blindaks** [comment]
@J0SAL Please assign this issue to me under GSSOC'23.

**Comment by J0SAL** [comment]
Small grammatical mistakes won't be considered under gssoc. do you still want to contribute to it? @blindaks

**Comment by J0SAL** [comment]
closing as there is no update
