### ISSUE TITLE
Add  some other Section

### ISSUE THREAD

**Issue by dheeraj1129** [J0SAL/Decentralized-Expense-Tracker#138]
### Is your feature request related to a problem? Please describe.

1. improve the navbar and add some image heading on the home page 
2. At least add About section in the navbar 

### Describe the solution you'd like

there and only a few headings and features add some more headings and  features images

### Additional context

Assign me this takes under GSSOC'23

**Comment by J0SAL** [comment]
There are already existing issues, please check those out first... #102 #101 etc..
