### ISSUE TITLE
Background image

### ISSUE THREAD

**Issue by BhartiNagpure** [J0SAL/Decentralized-Expense-Tracker#139]
### Is your feature request related to a problem? Please describe.

First page is looking incomplete as they contain only connect word  on it .

### Describe the solution you'd like

I  would like to add background image..

**Comment by J0SAL** [comment]
Yes, we need an image for our login page, Can you share the image and layout you have in mind? @BhartiNagpure

**Comment by BhartiNagpure** [comment]
> Yes, we need an image for our login page, Can you share the image and layout you have in mind? @BhartiNagpure

![Screenshot 2023-07-24 160519](https://github.com/J0SAL/Decentralized-Expense-Tracker/assets/104631882/f808a10d-1984-40a6-a4ce-efd394e8c6f1)

We can set this image to right side and connect button to left.

**Comment by J0SAL** [comment]
can you make it something like this, 
![image](https://github.com/J0SAL/Decentralized-Expense-Tracker/assets/52382282/c939d149-e94d-41cc-90b6-773fd4c12f32)

you can get this image from undraw.co if you search for 'welcome'

**Comment by BhartiNagpure** [comment]
> @BhartiNagpure can you make it something like this, ![image](https://user-images.githubusercontent.com/52382282/255691293-c939d149-e94d-41cc-90b6-773fd4c12f32.png)
> 
> you can get this image from undraw.co if you search for 'welcome'

Sure I can
