### ISSUE TITLE
Add Sepolia Testnet for Improved Testing Experience

### ISSUE THREAD

**Issue by kirtiraj22** [J0SAL/Decentralized-Expense-Tracker#14]
Description:
Currently, this project relies on the Goerli testnet for testing purposes. However, there are a couple of challenges that affect the usability and efficiency of our testing process. 

**Current State:**

1. **Goerli Faucet Minimum Requirement**: The Goerli testnet's faucet requires users to have a minimum of 0.001 ETH on the Ethereum mainnet to receive test ethers. This requirement creates a barrier for users who do not possess any ETH on the mainnet.

2. **Limited Test Ethers**: The Goerli testnet currently provides only 0.02 test ethers per day. This allocation is insufficient for testing the project.

**Proposed Solution:**

1. Introduce **Sepolia Testnet**: To overcome the limitations mentioned above, we propose adding the Sepolia testnet as an additional testing option. Sepolia offers a more user-friendly experience by providing a higher allocation of test ethers per day, enabling users to conduct extensive testing without being constrained by a limited supply of test ethers.

2. **Eliminate Mainnet ETH Requirement**: Unlike the Goerli testnet, the Sepolia testnet does not require users to possess any ETH on the Ethereum mainnet. This removes the prerequisite of having a minimum amount of ETH on the mainnet, making it more accessible to all users, especially those who are new to Ethereum testing.

I would like to make the above changes under GSSOC'23

**Comment by Arpaninformationtech** [comment]
Looking at the issue I believe I can contribute significantly, can you please assign me this issue.

**Comment by J0SAL** [comment]
Thanks for opening the issue @kirtiraj22, go ahead 🚀
