### ISSUE TITLE
Improving Button and Image on home page

### ISSUE THREAD

**Issue by Dimple-Choudhary** [J0SAL/Decentralized-Expense-Tracker#140]
### Is your feature request related to a problem? Please describe.

The illustration seem small and the button  can have more attractive hover effect :)  

### Describe the solution you'd like

Increasing  illustration height and  adding  the following hover effect on button of contact wallet :-

https://github.com/J0SAL/Decentralized-Expense-Tracker/assets/96401557/c94a58c9-6e39-4ca8-aabf-e819a249e41f

  

### Additional context

@J0SAL   will you assign me this issue under GSSOC'23.

**Comment by J0SAL** [comment]
That's a good suggestion @Dimple-Choudhary  but, We don't need it for now.
