### ISSUE TITLE
[Change] Changing the way to enter date through Calender

### ISSUE THREAD

**Issue by varunlmxd** [J0SAL/Decentralized-Expense-Tracker#142]
### Is your feature request related to a problem? Please describe.

In the Date section selecting date through a calender is much faster and easier while compared to enter date manually, It took me nearly 4mins to figure out how to type date properly.

Please assign this issue to me under GSSoC'23
![Screenshot_20230805_183438](https://github.com/J0SAL/Decentralized-Expense-Tracker/assets/104298930/a55996f4-507f-4c06-a30a-e6b62a64eb14)

### Describe the solution you'd like

To make date selection smooth the calender logo must be functional in the form.

**Comment by J0SAL** [comment]
There's already a way to do this
![image](https://github.com/J0SAL/Decentralized-Expense-Tracker/assets/52382282/3d5916a5-d3b2-42cc-ad8c-06270910a419)

Can you check why it didn't work on your machine? Maybe we can create an issue for that @varunlmxd

**Comment by varunlmxd** [comment]
Hey @J0SAL when I tried in Mozilla it is working fine but there a issue when it I am using in chrome browser
Mozilla:
![Screenshot_20230807_174159](https://github.com/J0SAL/Decentralized-Expense-Tracker/assets/104298930/cf35ed1e-492f-4eef-8f2f-e71563e5bdd5)
Chrome:
![Screenshot_20230807_174450](https://github.com/J0SAL/Decentralized-Expense-Tracker/assets/104298930/4349c8f9-54d4-4459-8f7b-2a5ec7775e62)

**Comment by J0SAL** [comment]
OK, it worked in my Chrome browser, @varunlmxd I think it is a device-specific problem. can you look into it, if you find the solution, let me know.

**Comment by varunlmxd** [comment]
![Screenshot_20230808_145550](https://github.com/J0SAL/Decentralized-Expense-Tracker/assets/104298930/468a4448-50f6-4c80-a596-89650028aa01)
This is how my console look, i even got two downward arrow instead of one in Type and Category

**Comment by varunlmxd** [comment]
While running locally I got the same issue
![Screenshot_20230808_151035](https://github.com/J0SAL/Decentralized-Expense-Tracker/assets/104298930/61eeca7c-ac54-442e-a18f-7504f603c233)

**Comment by J0SAL** [comment]
@varunlmxd can you look for the component that is causing the error?
Idt it's related to the date component, as I'm getting the same error logs, but my date component still works
