### ISSUE TITLE
Dark Mode Toggler

### ISSUE THREAD

**Issue by Manishak798** [J0SAL/Decentralized-Expense-Tracker#143]
### Is your feature request related to a problem? Please describe.

Nowadays, every website has a feature of switching between the modes as per user's preferences and that is missing in yours. I want to make a dark mode toggler using HTML5, CSS3, and JavaScript that will provide users an ease to switch between the modes. I am willing to work on this issue kindly, assign this to me under GSSOC23.

### Describe the solution you'd like

I want to make a theme toggler inside the nav bar that will provide a switching functionality to the users.

### Describe alternatives you've considered

I have considered making a toggler functionality for switching between modes.

### Additional context

![image](https://github.com/J0SAL/Decentralized-Expense-Tracker/assets/90680330/59633d1f-82b2-4363-8028-62899dd0b567)

**Comment by J0SAL** [comment]
so this function is already under development, check #17
