### ISSUE TITLE
Want to add our Contributor page in the website

### ISSUE THREAD

**Issue by HimanshuNarware** [J0SAL/Decentralized-Expense-Tracker#144]
### Is your feature request related to a problem? Please describe.

Details
Is your feature request related to a problem? Please describe.
Our Contributors page in the website

### Describe the solution you'd like

Describe the solution you'd like
We can add a Contributors page in the website. which is shows the name and the profile image of the contributor.and the number of commits is done by the contributor

**Comment by J0SAL** [comment]
good idea @HimanshuNarware, but not needed in the current implementation
