### ISSUE TITLE
Adding Contributor Workflow to Documentation

### ISSUE THREAD

**Issue by Jiggy9** [J0SAL/Decentralized-Expense-Tracker#15]
I am a contributor to GSSOC'23, an open-source project. I would like add a contributor workflow to the documentation. Could you please assign this issue to me? @J0SAL

**Comment by J0SAL** [comment]
Hey @Jiggy9!
There are a few changes made to the project documentation, that I believe are similar to your issue.
If you think you can add something extra, do mention it in the description in a little more detail

**Comment by Jiggy9** [comment]
Hey @J0SAL Thank you for your response! I noticed that there have been some changes made to the project documentation, but I would like to add a section on 'How to start contributing' that includes all the major basic steps. This section will cover everything from forking the repository, opening it on a local device, creating a new branch, making modifications, merging it into the master branch,  sending a pull request and wait till it is reviewed and merge.

I believe this section is crucial as it provides newcomers with a clear understanding of the contribution process. By following these steps, contributors can effectively participate in the project. Once I've added this section, you can review it and provide feedback on any missing or necessary information.

**Comment by J0SAL** [comment]
I believe those guidelines are already present [here](https://github.com/J0SAL/Decentralized-Expense-Tracker/blob/main/CONTRIBUTING.md)

**Comment by Jiggy9** [comment]
Yes thank you I just noticed it.
