### ISSUE TITLE
Improving the readme file 

### ISSUE THREAD

**Issue by harshsingh32** [J0SAL/Decentralized-Expense-Tracker#16]
I would like to improve the readme file of this project making it engaging for the users and make it more expressive.

**Comment by harshsingh32** [comment]
I would like to work on this issue, please assign this issue to me under GSSoC'23.

**Comment by SamridhiNancy** [comment]
"Hi there! I'm excited to contribute to this project for GSSOC'23'. I've taken a look at the codebase and I believe I can make some valuable improvements. I'll start working on it right away. If you have any specific requirements or suggestions, please let me know. Looking forward to collaborating with you all on this! ""

**Comment by J0SAL** [comment]
Hi @harshsingh32, @SamridhiNancy, could you elaborate on how you plan on making it better?

**Comment by harshsingh32** [comment]
I would improve the readme using catchy phrases and expressive information about the project. Using symbols and engaging information to engage the users to the project and they motivate to contribute to the project.

**Comment by astha-05** [comment]
I am interested in improving the readme using easily understandable information. So that it becomes easier for others to understand and get started. I have relevant experience to work on this readme file. Please consider and assign this to me
