### ISSUE TITLE
[Add] Favicon & [Improve] Texts

### ISSUE THREAD

**Issue by apneduniya** [J0SAL/Decentralized-Expense-Tracker#18]
I would like add favicon to make it more legit as well as I would like to remove text decorations or color of <a> tag from footer and instead of that I would design it a bit. 

I want to contribute this for you :)

**Comment by Sathvik902** [comment]
I would like to contribute to this issue as a part of @GSSOC'23
Please assign it to me. Thank you.

**Comment by J0SAL** [comment]
HI @apneduniya, @Sathvik902,
Can you add screenshots so that I can get a better understanding of the changes?

**Comment by Sathvik902** [comment]
@J0SAL ,
We can add fonts like

![image](https://github.com/J0SAL/Decentralized-Expense-Tracker/assets/92165565/d274f8a7-ba36-464c-b581-350698a63eec) 
or
![image](https://github.com/J0SAL/Decentralized-Expense-Tracker/assets/92165565/dad4eaff-cea4-4cf0-806c-96cdd50a4ca3)

Or mention any specific fonts, I'll add the font-style.



We can also add a more attractive favicons like:

![image](https://github.com/J0SAL/Decentralized-Expense-Tracker/assets/92165565/8e270e49-3b2b-4eec-9d9c-3700375e7c97) ![image](https://github.com/J0SAL/Decentralized-Expense-Tracker/assets/92165565/2ccf5e55-5208-4fa2-83dd-9cad05ef6518) ![image](https://github.com/J0SAL/Decentralized-Expense-Tracker/assets/92165565/a04c6dbe-90c3-4e38-9cd0-000666c17dd5) 
![image](https://github.com/J0SAL/Decentralized-Expense-Tracker/assets/92165565/1d06b76b-5c4b-442a-b004-132d51633cf8) ![image](https://github.com/J0SAL/Decentralized-Expense-Tracker/assets/92165565/4190b316-1222-4178-a039-f46fb6b01103) 
![image](https://github.com/J0SAL/Decentralized-Expense-Tracker/assets/92165565/91276ad0-498a-4030-b17b-35f293a99f8f) ![image](https://github.com/J0SAL/Decentralized-Expense-Tracker/assets/92165565/61402bcc-e41b-4bc4-b8e3-c14a72863103)


These would look great and relevant to your website.
Please assign it to me. Thanks.

**Comment by apneduniya** [comment]
> HI @apneduniya, @Sathvik902, Can you add screenshots so that I can get a better understanding of the changes?

By removing text decoration or create it more attractive:

![image](https://github.com/J0SAL/Decentralized-Expense-Tracker/assets/113763427/aeeb2ce5-fc74-4dc7-ad9b-8fe19e4c50d6)

I feel like there is not much problem with fonts family but I wanna add text animations like [MakeSurge]( https://www.makesurge.co) by using libraries like framer motion, etc.

Now, for favicons:

![image](https://github.com/J0SAL/Decentralized-Expense-Tracker/assets/113763427/dfc88aa5-b68a-4a80-9859-3f166cfe8c1c)
![image](https://github.com/J0SAL/Decentralized-Expense-Tracker/assets/113763427/a85d6e5c-9078-4faf-bd80-9112cc25682f)

As commented screenshots by Josal I can also do that however you can judge me better by seeing my previous projects like [MakeSurge](https://www.makesurge.co) or my own portfolio website [My website](www.thatsmeadarsh.co).

**Comment by Shyam1128** [comment]
![money-management](https://github.com/J0SAL/Decentralized-Expense-Tracker/assets/90980739/cabc05d7-c85b-401d-8498-c7ceeed2d6f6)
![Expense tracker](https://github.com/J0SAL/Decentralized-Expense-Tracker/assets/90980739/a7541ee5-4793-401d-bbc2-6a7f79d5891d)

Give a look over these kind of favicons as an example i guess this would be relevant to the website as favicon plays crucial role. We can change the footer  style and appearance with using some really nice fonts 

I am good at UI/UX part so u can consider to me to work on this issue 
Thanking you

**Comment by astha-05** [comment]
Favicons pay a vital role in branding and making the platform appealing for the users. For example we can add favicon of **piggy bank**. Clear and concise text will enhance the readibility we can make use copywriting for writing the catchy titles. For example **Bebas Neue, Roboto Condensed, Raleaway** fonts can be added. Please assign me this issue as I have keen interest in designing UI/UX.
Thank you

**Comment by apneduniya** [comment]
Aree yar I created the issue so I would only get assigned for this @astha-05 @J0SAL, create your own issues

**Comment by J0SAL** [comment]
go ahead @apneduniya
