### ISSUE TITLE
Improving UI of the Landing Page

### ISSUE THREAD

**Issue by Hemant2335** [J0SAL/Decentralized-Expense-Tracker#19]
I think your landing page is just fine and need some magic of css and animation . Please give me a chance to enhance that for you

therefore , please assign me above task under GSSOC'23

Thank you

**Comment by Sathvik902** [comment]
I would like to contribute to this issue as a part of @GSSOC'23
Please assign it to me. Thank you.

**Comment by J0SAL** [comment]
Hi @Hemant2335 , @Sathvik902
I do agree that the landing page is kinda cluttered and has scopes for improvement.
but, could you add more description/visuals on how you plan on making those changes?

**Comment by Sathvik902** [comment]
Sure!

**First of all, Making a landing page attractive by adding some of the animations.
Example:**

![image](https://github.com/J0SAL/Decentralized-Expense-Tracker/assets/92165565/83b76788-9116-4c5e-8d75-cdebc806fc25)

**OR**

![image](https://github.com/J0SAL/Decentralized-Expense-Tracker/assets/92165565/aa070450-b064-446d-82de-8b2a20193384)

You can tell me the specific customized themes or colors you want.

Also, Adding some cool animations to the website.

**Secondly, Adding a different footer to the site**
**For Example:**

![image](https://github.com/J0SAL/Decentralized-Expense-Tracker/assets/92165565/dd08c2b3-80af-4dfa-b1fb-7dfdcebc7f55)

**OR**

![image](https://github.com/J0SAL/Decentralized-Expense-Tracker/assets/92165565/2d028c00-500f-476e-aee2-69717e1d45bf)

**Comment by Hemant2335** [comment]
> Hi @Hemant2335 , @Sathvik902 I do agree that the landing page is kinda cluttered and has scopes for improvement. but, could you add more description/visuals on how you plan on making those changes?

Yaa I have Some Prototypes that I can design for you

attached images
![Screenshot (54)](https://github.com/J0SAL/Decentralized-Expense-Tracker/assets/85656999/97835220-a166-4771-bb0c-333b04e07ce1)
![Screenshot (53)](https://github.com/J0SAL/Decentralized-Expense-Tracker/assets/85656999/bd299241-7ebc-464a-b177-e4e533417120)

**Comment by Sathvik902** [comment]
Please Assign me to this. Thank you.

**Comment by Google-Ka-Dinosaur** [comment]
Hey there!! I would also like to contribute to this project by improving its UI. I am sharing this as one of the possible designs that could be implement. It has been designed using tailwind css as a part of one my practice projects. Kindly consider assigning me this issue if you like the design. Thank you.
![Screenshot (186)](https://github.com/J0SAL/Decentralized-Expense-Tracker/assets/98577878/145d6c4c-8769-40ea-b2ad-65eb23f5894e)


![Screenshot (187)](https://github.com/J0SAL/Decentralized-Expense-Tracker/assets/98577878/aa095f55-b20f-44ed-b942-6d22c98d0a86)

**Comment by J0SAL** [comment]
hey, this work is already in progress here #49
