### ISSUE TITLE
ADDING A SECTION OF EXPENSE TRACKING WITHOUT CONNECTING WALLET TO THE SITE 

### ISSUE THREAD

**Issue by Shashwat0227** [J0SAL/Decentralized-Expense-Tracker#23]
### Is your feature request related to a problem? Please describe.

Many people dont want to connect wallet to the site for security reasons , 

### Describe the solution you'd like

so i can make one section beside the connect wallet section and link it to a interface where people can add their expenses manually everyday .

**Comment by heyhimansh** [comment]
Hey @Shashwat0227, you just need the same feature without connecting any wallet ?

**Comment by J0SAL** [comment]
Hey, @Shashwat0227 How do you plan on storing the data on the blockchain without connecting the wallet?
