### ISSUE TITLE
[Add] login Page

### ISSUE THREAD

**Issue by Tathagt** [J0SAL/Decentralized-Expense-Tracker#25]
### Is your feature request related to a problem? Please describe.

I saw that there is no login Page 

### Describe the solution you'd like

It's better to add a login Page in the first page

**Comment by samarthhapse** [comment]
Hello, I am glad to tell that I am pretty good at designing part of websites and I'm excited to contribute to this project 'GSSOC'23  I've taken a look at the codebase and I believe I can make some valuable improvements. I'll start working on it right away. If you have any specific requirements or suggestions, please let me know. Looking forward for collaborating with you all on this.

Thanks !

**Comment by Pragati-3003** [comment]
Hey @Tathagt 
I would like to work on this issue. 
Please assign this issue to me under GSSOC'23. 
Thanks

**Comment by Shyam1128** [comment]
Hey @Tathagt I m good at designing the login page and i have much experience in UI/UX part so u can kindly consider me to work on this issue this will motivate me to work more on the issues like this under GSSOC'23
Thanking You

**Comment by astha-05** [comment]
Hey @Tathagt would like to work on this as I am well versed with web designing concepts. I went through the codebase and I believe that I can make some significant changes which will enhance the overall design. Please assign this issue to me under GSSOC'23
Thank you

**Comment by Sushilverma002** [comment]
I would like to work on this issue can u please assign me.

**Comment by Shubham1450** [comment]
would like to work on this issue can you please assign it to me.

**Comment by J0SAL** [comment]
@Tathagt, The first page is the login page, where the user has to log in by connecting the wallet
