### ISSUE TITLE
Add option to export the statement as pdf or image as well with download button.

### ISSUE THREAD

**Issue by imshvishal** [J0SAL/Decentralized-Expense-Tracker#28]
There is only one option to export the statement currently in the form of Excel File. But it may sometime create inconvenience for the user to read the statement.

**__Solution__**: Add multiple options to export the statments like pdf or some image file. In this way pie chart representation can also be included with the statement so that user can take a very detailed look on statments.

I would like to make the changes accordingly under GSSOC'23.

**Comment by dk172923** [comment]
Hi I would like to work on this issue please this to me under GSSOC'23

**Comment by imshvishal** [comment]
@J0SAL Could you please check if this should be added as a feature or not?
If yes.. please assign it to me under GSSOC'23.

**Comment by J0SAL** [comment]
go ahead @imshvishal!
I believe only having a pdf will be good enough. Image is not required.

**Comment by imshvishal** [comment]
Sure, I will add only pdf option.

**Comment by imshvishal** [comment]
#65
