### ISSUE TITLE
Avoid gas optimization issues 

### ISSUE THREAD

**Issue by blessingblockchain** [J0SAL/Decentralized-Expense-Tracker#30]
### Describe the bug

To avoid the potential gas consumption issues in the 'getUserTransactions' , Consider using a more efficient data structure like a dynamic array or mapping to store and retrieve user transactions.

### Expected behaviour

This would reduce gas consumption and optimize the function

### Additional context

Hey @J0SAL so sorry, now submiting the issue, i hope it gets approved and assigned to me. Thank you!

**Comment by J0SAL** [comment]
The project is already using map to store the data. How to you propose to reduce the gas consumption, please elaborate?

**Comment by blessingblockchain** [comment]
As the number of transactions grows, the getUserTransactions function may consume significant gas due to the loop and array operations. Im proposing to reduce gas consumptions by  using pagination or other techniques to mitigate potential gas limitations when retrieving user transactions.

assign me this, so i can sollve issue. under GSSoc

**Comment by J0SAL** [comment]
Actually there are some different plans with respect to this, will create an issue for this soon
