### ISSUE TITLE
Add hover effect on "Add" button

### ISSUE THREAD

**Issue by dhrumishah** [J0SAL/Decentralized-Expense-Tracker#34]
### Is your feature request related to a problem? Please describe.

The "add" button doesn't have any hover effect nor any animation. Would like to add that.
I can work on this.

![image](https://github.com/J0SAL/Decentralized-Expense-Tracker/assets/84569241/f63e679d-7924-49f6-87c8-2aa223d9d520)

### Describe the solution you'd like

I will be adding pointer cursor and give some basic hover effect to make the button dynamic

**Comment by Shubham1450** [comment]
I would like to work on this issue can u please assign me. @dhrumishah

**Comment by iamFaizanArif** [comment]
Assign me!

**Comment by heyhimansh** [comment]
Hi @dhrumishah , I recently reviewed your website and codebase, and I noticed an opportunity to enhance the appearance of the "add" button doesn't have any hover effect nor any animation. I suggest making improvements by incorporating better hover effect with responsive design. I am confident that I can contribute significantly to enhancing the web page's appearance. Please assign this issue to me under GSSOC'23. Thank you!

**Comment by Sushilverma002** [comment]
can you please assign me this issue.

**Comment by Hritik1503** [comment]
I am interested to work on this issue please assign me this task under GSsoc

**Comment by sattvikdwivedi** [comment]
![Screenshot (46)](https://github.com/J0SAL/Decentralized-Expense-Tracker/assets/104271708/ce9b4cd2-05fe-42d7-9607-92542cb83be7)

 @J0SAL  I added the hover effect on the add button. Assign me this task for better enhancement

![Screenshot (45)](https://github.com/J0SAL/Decentralized-Expense-Tracker/assets/104271708/a2718fa4-3e50-4dd0-9263-ae01cd5ce179)

**Comment by sattvikdwivedi** [comment]
![Screenshot (45)](https://github.com/J0SAL/Decentralized-Expense-Tracker/assets/104271708/0f5d0b7d-ea7b-418d-90f4-942b5f3612fb)

I have been added the hover effect in "Add " button .Can you assign me this task for more enhancement and changes.

![Screenshot (46)](https://github.com/J0SAL/Decentralized-Expense-Tracker/assets/104271708/52368deb-6d26-4bb9-a873-e068758f8ecd)

**Comment by J0SAL** [comment]
Hey @dhrumishah, the behavior is intentional.
Till the form is incomplete, `Add` button will stay disabled, and hence there won't be any _hover-effect_.
However, once you fill out the form, you'll see that button will get enabled and will hence have _hover-effect_.
