### ISSUE TITLE
Add the details of wallets on dashboard available on connect wallet.

### ISSUE THREAD

**Issue by garimapahwa** [J0SAL/Decentralized-Expense-Tracker#35]
### Is your feature request related to a problem? Please describe.

Yes, providing the prerequisite information is necessary.

### Describe the solution you'd like

I want to add the details to be written on the dashboard so that people know the information about the wallet before opening a particular type of wallet.

**Comment by J0SAL** [comment]
Hey @garimapahwa, can you elaborate on what all information you plan on showing on the dashboard?

**Comment by SakshiShah29** [comment]
I would like to work on this issue. Please assign it to me under GSSoC'23.
