### ISSUE TITLE
[DOCS] Improving up the contributing.md

### ISSUE THREAD

**Issue by abhay-raj19** [J0SAL/Decentralized-Expense-Tracker#36]
### Description

Will be creating a cool and interactive contributing.md 

1.will also be improving up the installation guide style .
2.and will also add up the images for best and good results .

Pls do assign me up first ,for the best suggested changes .
Will be making it awesome and cool.

**Comment by YashNigam2503** [comment]
Is this issue still open? I can see contributing.md is already pretty good.

**Comment by J0SAL** [comment]
@abhay-raj19 As mentioned in the discord, we'll keep the documentation for the end
