### ISSUE TITLE
Adding Google Auth

### ISSUE THREAD

**Issue by Ishpreet-Kaur-Bedi** [J0SAL/Decentralized-Expense-Tracker#37]
### Is your feature request related to a problem? Please describe.

I can add login/ signup page along with Google auth.Please assign me this issue under GSSOC'23

### Describe the solution you'd like

we can ad a login sign up page along with google and github authentication

**Comment by Aditi323** [comment]
Could you please assign me this as a GSSOC Contributor.

**Comment by J0SAL** [comment]
Hey @Ishpreet-Kaur-Bedi, could you please elaborate on why do you think this feature is needed?
