### ISSUE TITLE
No Check for Duplicate transactions being created.

### ISSUE THREAD

**Issue by infoparth** [J0SAL/Decentralized-Expense-Tracker#41]
### Describe the bug

The addExpense and addIncome functions in the smart contract do not check if the _id parameter is already in use. This could lead to duplicate transactions being created, at the same time.

### Expected behaviour

The addExpense and addIncome functions should first check if the _id is already in use, and if it is, no write function should be done on them, while the id is in use.

**Comment by infoparth** [comment]
please assign me this issue under gssoc 23, I will fix this bug.

**Comment by J0SAL** [comment]
Hey @infoparth , I believe this line does the job `require(all_ids[_id] == false, "invalid id");`
