### ISSUE TITLE
Checking the validity of transaction before deleting.

### ISSUE THREAD

**Issue by KritikaJoshi22** [J0SAL/Decentralized-Expense-Tracker#42]
### Describe the bug

The deleteTransaction function does not check if the id parameter is a valid transaction. This could lead to an invalid transaction being deleted.

### Expected behaviour

The function should first check, if the transaction which is being deleted is a valid one or not

**Comment by KritikaJoshi22** [comment]
please assign me this issue under GSSoC '23, I will fix it..

**Comment by J0SAL** [comment]
Hey @KritikaJoshi22, are you planning on making changes to the contract? If yes, can you elaborate on how you will check if the transaction is valid?
