### ISSUE TITLE
Improvement in the styling of the form

### ISSUE THREAD

**Issue by SakshiShah29** [J0SAL/Decentralized-Expense-Tracker#44]
### Is your feature request related to a problem? Please describe.

I wish to improve the ui of the Add Transaction form 
![image](https://github.com/J0SAL/Decentralized-Expense-Tracker/assets/65860201/c1bab2d2-1763-4f6c-a705-aa52e178d3f5)

### Describe the solution you'd like

I would like to add some neumorphism and a bit of animation to the add button

### Additional context

I wish to contribute to it and I would request you to assign me this issue under GSSoC'23

**Comment by J0SAL** [comment]
Hey @SakshiShah29, 
Can you be more specific? like what kind of changes are you planning, if possible, any screenshots would really help.

**Comment by J0SAL** [comment]
sounds good, go ahead @SakshiShah29
