### ISSUE TITLE
Enhancement in the header and footer

### ISSUE THREAD

**Issue by Abhishek-465** [J0SAL/Decentralized-Expense-Tracker#45]
### Is your feature request related to a problem? Please describe.

 The footer is not looking good. The link style should be rectified. 

### Describe the solution you'd like

I want to modify the  nav bar as well as the footer using HTML and CSS.

**Comment by J0SAL** [comment]
issue #26 already exists for this, however it's not assigned yet, so can you propose your changes there.

**Comment by Abhishek-465** [comment]
Okay then i am working on it.
