### ISSUE TITLE
Improve home page frontend

### ISSUE THREAD

**Issue by ojasaklechayt** [J0SAL/Decentralized-Expense-Tracker#49]
### Is your feature request related to a problem? Please describe.

I want to add frontend for large screen devices.

### Describe the solution you'd like

I have some improvements for the home page frontend part of the website.

**Comment by khushiminda** [comment]
I AM A UI/UX DESIGNER
so for a responsive Homepage-
i will-
Plan my layout
Use a responsive framework
Design for mobile-first
Use media queries
Test across devices
Provide touch-friendly interactions
I can make this more responsive.
assign this to me under gssoc'23.

**Comment by gurjeetsinghvirdee** [comment]
> ### Is your feature request related to a problem? Please describe.
> I want to add frontend for large screen devices.
> 
> ### Describe the solution you'd like
> I have some improvements for the home page frontend part of the website.
> 
> ### Describe alternatives you've considered
> _No response_
> 
> ### Additional context
> _No response_

Can you elaborate what improvements you want to do?

**Comment by ojasaklechayt** [comment]
> Can you elaborate what improvements you want to do?  @ojasaklechayt 

Okay, so as we open the home page. All we were seeing was a small photo and a button to connect the wallet.

I have added a heading saying welcome to the expense tracker and increased the size of image.

**Comment by ojasaklechayt** [comment]
> Can you elaborate what improvements you want to do?  @ojasaklechayt 

Actually I have already made a Pr @gurjeetsinghvirdee

**Comment by gurjeetsinghvirdee** [comment]
Can you attach a SS? 
@J0SAL will check if we had to add this thing or not

**Comment by gurjeetsinghvirdee** [comment]
> > Can you elaborate what improvements you want to do?  @ojasaklechayt
> 
> Actually I have already made a Pr @gurjeetsinghvirdee

Please close that PR it would be invalid if you make it without assigning

**Comment by ojasaklechayt** [comment]
> > > Can you elaborate what improvements you want to do?  @ojasaklechayt
> > 
> > Actually I have already made a Pr @gurjeetsinghvirdee
> 
> Please close that PR it would be invalid if you make it without assigning

I see okay 👍

**Comment by ojasaklechayt** [comment]
> > > Can you elaborate what improvements you want to do?  @ojasaklechayt
> > 
> > Actually I have already made a Pr @gurjeetsinghvirdee
> 
> Please close that PR it would be invalid if you make it without assigning

Can you please assign this to me?

**Comment by gurjeetsinghvirdee** [comment]
@J0SAL will do if he likes the idea

**Comment by J0SAL** [comment]
go ahead, @ojasaklechayt! 🚀
you can try creating a title as "Welcome to Jarvis"
Also please make sure the UI stays responsive.

**Comment by J0SAL** [comment]
will be worked on under #139
