### ISSUE TITLE
[DOCS] <description>

### ISSUE THREAD

**Issue by Anugyagupta43** [J0SAL/Decentralized-Expense-Tracker#54]
### Description

Hey I would like to update the README file so that It can give more information about the project.
I would also like to translate it in Hindi language for Hindi speakers to understand the project better.

**Comment by J0SAL** [comment]
Hey @Anugyagupta43, it's a great thing to consider! 
but for now, it's not what I want to focus on, maybe sometime in the future, when the product is ready to be rolled out.
