### ISSUE TITLE
Function call Information in logs

### ISSUE THREAD

**Issue by MrSahilShaikh** [J0SAL/Decentralized-Expense-Tracker#56]
### Is your feature request related to a problem? Please describe.

There is no event call after calling function from frontend. We don't get any information in logs of blockchain. User / admin dont know what that function do. or what values gone in that parameter. 

### Describe the solution you'd like

I want to add event in solidity function after every function call we get the info of that function what is done by this function feature in logs.

### Describe alternatives you've considered

Lack of Event Logging: It's a good practice to emit events for important contract state changes. Consider adding events to log in addIncome , addExpense , getUserTransactions which can make it easier to track and analyze contract activity.

### Additional context
I want to work under GSSOC'23 .. Can you assign me this issue .I am proficient in Solidity and Smart contract @J0SAL

**Comment by J0SAL** [comment]
go ahead @MrSahilShaikh 🚀
