### ISSUE TITLE
Add a custom 404 not found page [GSSoC'23]

### ISSUE THREAD

**Issue by Sukhendu2002** [J0SAL/Decentralized-Expense-Tracker#6]
Add a custom  404 not found page
Can you assign this to me, I want to work on this under GSSoC'23

**Comment by Thrillseekr** [comment]
Hey @J0SAL ,
I'm Darshan Jain, and I'm thrilled to be a part of this GSSOC'23. I bring along my expertise in HTML5, CSS, PHP, Bootstrap, and creativity too. I'm passionate about open source projects and eager to contribute and collaborate with fellow enthusiasts.

Can you please assign this to me.

**Comment by AmanMittal-3305** [comment]
Hii,
I would like to work on this issue

**Comment by Umesh7Dixit** [comment]
@J0SAL can you assign me this issue I can make this

**Comment by Aman2818** [comment]
@J0SAL I want to work on this issue please assign me

**Comment by Anushka20365** [comment]
Hello @J0SAL ,
I'm Anushka Anand . I want to work on this issue under Gssoc'23. I am really eager to work on open source projects and contribute to this community.

Skills
HTML5, CSS3, JS, Bootstrap |  Python, Django | Php, mysql | MERN | Responsive Design | Adobe Photoshop | 

Can you please assign this issue to me.

**Comment by SonamMalik17** [comment]
@J0SAL 
I would like to work on this issue,  I am good at designing 
I have worked on more than 30 designs on Canva and I have knowledge of HTMl, CSS, Bootstrap,  Javascript and I have tried tried my handout in Node and express and I took keen interest in learning MERN Stack Web Development.

**Comment by AmshuGM** [comment]
Hello @J0SAL 
 I'm thrilled to work on the Custom 404 Not Found page for GSSoC'23. With expertise in PHP, HTML, CSS, and Bootstrap, I'm eager to contribute. Please assign me this task on GitHub. 
It's my first time in GSSOC and I assure you to give my best.
Thank you!"

**Comment by Shaurya10101** [comment]
Hello @J0SAL , I hope you are well
I am really excited to work on this project , its a humble request to assign this issue to me . I would use my expertise in HTML,CSS,Next.Js and Bootstrap . It would be a pleasure to design this page . I'll give my best and hope to fulfill your expectations 
Thank You !!

**Comment by Suchitra-Sahoo** [comment]
Hello @J0SAL . I came across your project  and I'm really interested in contributing by adding a 404 page to the website. I have experience in web development especially HTML, CSS , javascript , designing and Bootstrap . I can design a 404 page  ensuring it matches the overall theme of the website . If you are open to collaboration I would be happy to take this task. I look forward to hearing from you.
Best Regards
Suchitra Sahoo

**Comment by J0SAL** [comment]
it would be easier to decide if you could show a screenshot of your design. Then we can choose the one we prefer

**Comment by Shaurya10101** [comment]
I don't have the design ready yet in screenshot but I have the idea i.e - 
A big 404 with the monopoly guy in between the space of zero that appears to comeout of that space

**Comment by Thrillseekr** [comment]
@J0SAL 
![HTML-404-Page-Template](https://github.com/J0SAL/Decentralized-Expense-Tracker/assets/118781875/dcb7d6c0-9a38-482e-a3bf-b76289d0975a)

**Comment by iamFaizanArif** [comment]
Please assign it to me under GSSoC'23.

**Comment by Google-Ka-Dinosaur** [comment]
![Screenshot (188)](https://github.com/J0SAL/Decentralized-Expense-Tracker/assets/98577878/a4bf4f10-87f0-4e5b-8333-544d5158a28f)

Hey @J0SAL , this is one error page idea had implemented in my previous projects. I could do something similar like an ethereum icon with cracks in it  saying "The page Wasn't Found." Although I don't have any visuals to present my idea however I feel that I will be able to successfully implement it. Kindly consider assigning me this issue . Thank you.

**Comment by J0SAL** [comment]
@Thrillseekr your design doesn't give a proper context for **page not found**

@Google-Ka-Dinosaur 's Design is good, can you also add some icons to it?

**Comment by Google-Ka-Dinosaur** [comment]
@J0SAL yes I can add some icons like one to go back to the main page

**Comment by HimanshiDafouty** [comment]
I request you to kindly assign me this project. As I can provide relevant outcomes.Here, I am attaching one
![404](https://github.com/J0SAL/Decentralized-Expense-Tracker/assets/116953498/aa7e9043-d209-4f77-a09c-69159741d7d7)

**Comment by J0SAL** [comment]
go ahead, @Google-Ka-Dinosaur 🚀
