### ISSUE TITLE
to make the animation in pictures

### ISSUE THREAD

**Issue by Nikitaparmar04** [J0SAL/Decentralized-Expense-Tracker#60]
### Describe the bug

there is no bug that looks good.when i adding up some features

### Expected behaviour

that look so nice and show more attractive in website and i add so much new features on it this may be helpful. please assign me this project

**Comment by J0SAL** [comment]
Hey @Nikitaparmar04, Can you share more details on what pictures/animations you want to add and what components it'll be affecting?

**Comment by Kajal2468** [comment]
I want to work on this issue please assign it to me @Nikitaparmar04 

Thank You!!!

**Comment by J0SAL** [comment]
@Kajal2468 this issue won't be a part of GSSoC'23 are you still willing to do it?
