### ISSUE TITLE
Working with the wallet extensions.

### ISSUE THREAD

**Issue by fatemaker254** [J0SAL/Decentralized-Expense-Tracker#61]
### Is your feature request related to a problem? Please describe.

After opening the site it is requested to connect my wallet but it is not working if i am having a wallet extension and it is required to download the wallet app. 

### Describe the solution you'd like

Adding a feature to connect with both wallet app or extension which one is present or having the first priority for the app and then if the app is not present then check for the extension to connect.

**Comment by J0SAL** [comment]
I am not getting what error you are facing, could you share a screenshot for the same?
