### ISSUE TITLE
Front End: Wallet profile

### ISSUE THREAD

**Issue by engorgedspirit** [J0SAL/Decentralized-Expense-Tracker#62]
### Describe the bug

If we click on the wallet address on top, it directly disconnects and we have to connect again. This might be a huge problem for users who are not familiar with interface.

### Expected behaviour

Instead we can ask for a confirmation to disconnect when clicked, also a description that click here to disconnect. Or can implement a dropdown which shows details for wallet and gives option to disconnect.

### Screenshots

![image](https://github.com/J0SAL/Decentralized-Expense-Tracker/assets/85272049/5ca47644-3190-4e21-88c5-908ff3f3be09)

I'm a GSSoC contributor and please assign me this issue.

**Comment by J0SAL** [comment]
Go ahead @engorgedspirit

**Comment by ikavinkumar** [comment]
Can I take part in this issue

**Comment by J0SAL** [comment]
@engorgedspirit are you working on this?

**Comment by ikavinkumar** [comment]
Yes
