### ISSUE TITLE
transaction failed

### ISSUE THREAD

**Issue by engorgedspirit** [J0SAL/Decentralized-Expense-Tracker#63]
### Is your feature request related to a problem? Please describe.

Its too small, users may miss it.
![image](https://github.com/J0SAL/Decentralized-Expense-Tracker/assets/85272049/cbf363bc-9d86-4d90-bc00-3dab3e9513fe)

### Describe the solution you'd like

We can make it bigger or more noticeable than it is now.
I'm a GSSoC contributor and please assign me this issue.

**Comment by J0SAL** [comment]
Hey @engorgedspirit, Can you share the screenshot of the error message you want to show to the users?
