### ISSUE TITLE
Addition of Code of Conduct

### ISSUE THREAD

**Issue by preetimahto17** [J0SAL/Decentralized-Expense-Tracker#64]
### Description

I kindly request the inclusion of a code of conduct in the repository because it:

1. Promotes inclusivity and respect.
2. Defines acceptable behavior.
3. Encourages healthy collaboration.
4. Resolves conflicts effectively.
5. Protects contributors and maintainers.
6. Aligns with open source values.

**Comment by gurjeetsinghvirdee** [comment]
What's you contribution in this issue?
Github Provides Code of Conduct template you just have to add mail or name 

I don't think there is a need of this
what you say @J0SAL
