### ISSUE TITLE
Addition of env.example file in the backend folder

### ISSUE THREAD

**Issue by coder12git** [J0SAL/Decentralized-Expense-Tracker#66]
### Is your feature request related to a problem? Please describe.

You have mentioned in the readme to add the environment variables to the .env file in the backend folder. But to add those env variables people have to create that file which is not an ideal way.  Instead, we can create an env. example file in the backend folder and mention all those environment variables there, and then on readme or in contribution.md you can mention just to rename that file to .env and put the values of those env variables in that file.
Also, I want to add a Code Of Conduct file in the root directory of the project.

Please assign me this issue. I am a contributor in GSSOC 2023.

![Screenshot 2023-05-27 101502](https://github.com/J0SAL/Decentralized-Expense-Tracker/assets/108334168/55ad6ec9-4733-4924-8b36-28eaa0c8b66a)

### Describe the solution you'd like

I want to add env.example file in the backend folder. Additionally, I also want to add Code Of Conduct file in the root directory of the project.

**Comment by coder12git** [comment]
@J0SAL Assign me this issue!

**Comment by J0SAL** [comment]
Thanks for opening the issue @coder12git, go ahead 🚀

**Comment by J0SAL** [comment]
It would be great if you create 2 PRs, one for the example.env and the other one for the code of conduct.

**Comment by coder12git** [comment]
Sure
