### ISSUE TITLE
I want to add sitemap to this website. I have all the skills required.  Please assign me this issue ,I want to work on this issue under the GSSoC'23

### ISSUE THREAD

**Issue by mayank123op** [J0SAL/Decentralized-Expense-Tracker#67]
### Is your feature request related to a problem? Please describe.

yes this feature request is related to problem faced . 

### Describe the solution you'd like

 it helping designers understand the number of pages on the site and how they are laid out . It help user to navigate site easily.

**Comment by J0SAL** [comment]
@mayank123op can you share what design you have planned?

**Comment by mayank123op** [comment]
I want to do this work in XML format.

**Comment by J0SAL** [comment]
okay, so we don't need it for now, you can trying looking at some other functionality
