### ISSUE TITLE
creating a dash board to facilitate the user

### ISSUE THREAD

**Issue by CK-chirag** [J0SAL/Decentralized-Expense-Tracker#69]
### Is your feature request related to a problem? Please describe.

the user can not see his/her details
if he/she wish to the change the username of any other necessary details..

### Describe the solution you'd like

the user can see his/her details in dashboard and can also login/logout the website 

### Describe alternatives you've considered

a button can be created on top right corner where user icon will be shown 

### Additional context

Pls assign this issue to me under gssoc'23 tag

**Comment by J0SAL** [comment]
We don't need this as the login function is simply handled by the wallet
