### ISSUE TITLE
Want to logo in the Navbar

### ISSUE THREAD

**Issue by HimanshuNarware** [J0SAL/Decentralized-Expense-Tracker#74]
### Is your feature request related to a problem? Please describe.

Navbar content default react js logo, I want to change it to like the favicon of the website, it improves the UI of the website

##Screenshot
![69](https://github.com/J0SAL/Decentralized-Expense-Tracker/assets/83147410/cf263d02-d92f-4212-95a0-dd866b86f6ab)

### Describe the solution you'd like

I want to add a similar logo as the favicon of the website. it match with the subject of the website

**Comment by gurjeetsinghvirdee** [comment]
Can you attach SS of new favicon or logo

**Comment by HimanshuNarware** [comment]
> Can you attach SS of new favicon or logo

I want to add the same logo as the website favicol have
#ss

![91](https://github.com/J0SAL/Decentralized-Expense-Tracker/assets/83147410/30fd81ec-ce1d-4930-b1d8-9cbb476b8ab7)

**Comment by HimanshuNarware** [comment]
> It looks like a vercel favicon

yep i want to add this icn into navbar icn

**Comment by J0SAL** [comment]
> > It looks like a vercel favicon
> 
> yep i want to add this icn into navbar icn

So compared to the Vercel Icon, the current one looks much better, thank you but I'll be closing the issue
