### ISSUE TITLE
Date comparison in input form isn't according to respective time zone.

### ISSUE THREAD

**Issue by imshvishal** [J0SAL/Decentralized-Expense-Tracker#75]
Since there is 5hrs 30 min difference between Indian time zone and GMT so it errors when we input form after 12AM and before 5:30AM IST because the date with which the date input data is being compared is in GMT.
![image](https://github.com/J0SAL/Decentralized-Expense-Tracker/assets/67648158/5ff2da12-9276-4ba1-be92-1e380e6b80d4)

Solution: This issue can be fixed by comparing the form date input with respective time zones.

I want to work on this issue so please assing this to me under gssoc23.

**Comment by J0SAL** [comment]
Glad someone noticed this issue.
Go ahead @imshvishal 🚀
