### ISSUE TITLE
Addition of Text with Heading in Homepage

### ISSUE THREAD

**Issue by iamRabia-N** [J0SAL/Decentralized-Expense-Tracker#77]
### Is your feature request related to a problem? Please describe.

No. It's enhancement in the existing design. The homepage is too clear which makes user doubt on whether he/she is on actual web or not.

### Describe the solution you'd like

1. Adding web name heading to the center of page as : Welcome to Jarvis
2. Then 2-3 line informational guideline explaining what this website about.
This text will be above the "Connect Wallet" button.
This will make homepage look even better.

### Describe alternatives you've considered

Addition of text and images on the homepage

### Additional context

N/A

**Comment by J0SAL** [comment]
please look  at #49
