### ISSUE TITLE
footer development

### ISSUE THREAD

**Issue by Hardik-2311** [J0SAL/Decentralized-Expense-Tracker#81]
### Is your feature request related to a problem? Please describe.

@J0SAL it is scrolling up and down which doesnt give the best ui/ux 

### Describe the solution you'd like

firstly i will work on developing user section and then using css fix the error

### Describe alternatives you've considered

complete revamp of the footer section 

### Additional context

kindly provide me this issue and add label under gssoc  thankyou

**Comment by J0SAL** [comment]
hey @Hardik-2311, please include demo - screenshot for your proposal
