### ISSUE TITLE
HomePage enhancement 

### ISSUE THREAD

**Issue by ATOMworkplace** [J0SAL/Decentralized-Expense-Tracker#83]
### Is your feature request related to a problem? Please describe.

The homepage of the webpage is quite simple and a lot can be done to make it more engaging and interesting 
![Screenshot 2023-05-30 140041](https://github.com/J0SAL/Decentralized-Expense-Tracker/assets/114564628/a2309cc1-69d4-41c1-aba4-0035e5bca6cd)

### Describe the solution you'd like

The whole webpage can be designed based on your readme part with the following additions
1. Addition of front image showing title and suitable background image
2. Addition of text showing features, demo, technology, and a video player will be added
3. Animated button (beat animation or similar) for connecting the wallet
4. Carousel for screenshots
5. Footer which will directly lead the user to the GitHub page for star

**Comment by J0SAL** [comment]
#49 already exist for this
