### ISSUE TITLE
Additions in Issue Template

### ISSUE THREAD

**Issue by Anshika-Jain02** [J0SAL/Decentralized-Expense-Tracker#95]
## Description:

*I noticed that the repository does not have an appropriate issue template.*

*Issue Template: I want to add  some more points to your issue template like styling changes, documentation, etc*

Please assign this issue to me under Gssoc'23 @J0SAL

**Comment by J0SAL** [comment]
Hey @Anshika-Jain02, there are already Issue templates created on [`./github/ISSUE_TEMPLATE/`](https://github.com/J0SAL/Decentralized-Expense-Tracker/tree/main/.github/ISSUE_TEMPLATE) do you mean to update those?

**Comment by Anshika-Jain02** [comment]
@J0SAL Sir, i want to add a new issue template style.yml to guide the contributors about the proper format in which they can raise their issues related to UI improvement or styling etc
