### ISSUE TITLE
Add some text content to the homepage [GSSoC'23]

### ISSUE THREAD

**Issue by 1Shubham7** [J0SAL/Decentralized-Expense-Tracker#96]
### Is your feature request related to a problem? Please describe.

The homepage of the website looks very blank. Some text about the website can be add as an intro to the website and tell the user what the website does.
![empty web](https://github.com/J0SAL/Decentralized-Expense-Tracker/assets/116020663/0d265d94-81e9-4418-b31a-76b1526e9539)

### Describe the solution you'd like

I can add some text as an intro to the website

### Additional context

Please assign me this issue under GSSoC'23

**Comment by 1Shubham7** [comment]
Please assign me this issue under GSSoC"23

**Comment by J0SAL** [comment]
It's already in progress on #49 or #55, you can contribute by commenting your suggestions there

**Comment by 1Shubham7** [comment]
ok @J0SAL .
