### ISSUE TITLE
Frontend : Add Eslint and prettier for code formate!

### ISSUE THREAD

**Issue by Hareesh108** [J0SAL/Decentralized-Expense-Tracker#98]
### Is your feature request related to a problem? 

Error detection: ESLint analyzes JavaScript code and identifies potential errors, such as syntax mistakes, variable misuse, undeclared variables, and more. It helps catch these issues early in the development process, reducing bugs and improving code reliability.

Code style enforcement: ESLint enforces coding style guidelines and conventions. It can detect and flag inconsistencies in code formatting, such as indentation, whitespace usage, line length, and the placement of semicolons. This promotes readability and makes the codebase more maintainable.

Best practices enforcement: ESLint provides rules that enforce JavaScript best practices. It helps identify potential issues or anti-patterns that could lead to bugs or performance problems. For example, it can flag the use of deprecated or unsafe APIs, suggest more efficient alternatives, or enforce the use of certain language features for better code quality.

Customizability: ESLint offers a wide range of configuration options and extensibility. It allows developers to tailor linting rules based on their specific project requirements, coding style preferences, or coding guidelines established within their team or organization.

Integration with development workflows: ESLint seamlessly integrates with various development tools and workflows, including text editors, IDEs, build systems, and continuous integration (CI) pipelines. It provides real-time feedback and can be configured to run automatically as part of the development process, ensuring code quality is maintained throughout the project lifecycle.

### Describe the solution you'd like

I would like to add configuration.

**Comment by Hareesh108** [comment]
@J0SAL Hey!! check the feature and assign it to me!!

**Comment by J0SAL** [comment]
Hey @Hareesh108, we don't need this for now
